/**
 * The sound palette. Every file is generated by `scripts/generate-sfx.js` —
 * short synthesized tones, no external assets to license.
 *
 * `require` is what Metro needs to bundle them, so the map is written out in
 * full rather than built from a loop.
 */
export const SOUND_FILES = {
  /** Keypad press. */
  tap: require('../../../../assets/sfx/tap.wav'),
  /** Verdicts: the same gesture pitched up or down. */
  higher: require('../../../../assets/sfx/higher.wav'),
  lower: require('../../../../assets/sfx/lower.wav'),
  correct: require('../../../../assets/sfx/correct.wav'),
  /** Round outcomes. */
  win: require('../../../../assets/sfx/win.wav'),
  lose: require('../../../../assets/sfx/lose.wav'),
  start: require('../../../../assets/sfx/start.wav'),
  eliminated: require('../../../../assets/sfx/eliminated.wav'),
  /** An opponent's guess landing on your board. */
  peer: require('../../../../assets/sfx/peer.wav'),
  /** Achievement earned. */
  unlock: require('../../../../assets/sfx/unlock.wav'),
  /** Staking a guess under Risk / Double down. */
  wager: require('../../../../assets/sfx/wager.wav'),
  /** Someone tapped a reaction. */
  react: require('../../../../assets/sfx/react.wav'),
} as const;

export type SoundName = keyof typeof SOUND_FILES;
